version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "nT9vR6tv"
      MYSQL_USER: 'kotm_2020'
      MYSQL_PASSWORD: 'nT9vR6tv'
      MYSQL_DATABASE: 'kotm_2020'
      TZ: 'America/Denver'
    networks:
      - custom


volumes:
  mysql:

networks:
  custom:
    external: true